[Task] Altera links sidebar
uxshop/design-system pull request #114
Opened 2023-05-02 12:36 UTC by kevenssousa

changes:
- altera nome dos links e adiciona icon para fechar sidebar

2023-05-02 12:49 UTC, antonydosreis requested changes

2023-05-02 12:49 UTC, antonydosreis commented on src/components/admin/sidebar/Sidebar.vue
>  const clickOverlay = () => {
Agora que este método não é mais chamado apenas no overlay, será que não seria melhor alterar o nome dele? Algo como simplesmente `toggleMenu`

2023-05-02 12:49 UTC, antonydosreis commented on src/components/admin/sidebar/Sidebar.vue
> +		<div v-if="menu.open" class="ui-close-sidebar" @click="clickOverlay"><img src="./close-icon.svg" alt="" /></div>
Não existe aqui a possibilidade de usar o nosso componente `Icon`?

2023-05-04 11:30 UTC, antonydosreis approved these changes

2023-05-04 12:02 UTC, simaomeyrerdooca approved these changes
@kevenssousa Quando a US for pra homolog me avisa pra colocarmos essa branch de feat do DS no admin, beleza?

2023-05-04 17:48 UTC, merged