[task] refatorar componente badge
uxshop/design-system pull request #153
Opened 2023-11-24 17:00 UTC by vitorbruski

## [task] refatorar componente badge 

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10069)

### changes:

- refatorada documentação de badge para typescript

2023-11-24 17:39 UTC, simaomeyrerdooca commented
neste mesmo PR podemos alterar o `.scss` para os novos tokens semânticos

2023-11-28 20:09 UTC, simaomeyrerdooca commented on src/components/ui/badge/Badge.stories.ts
> +export const Primary: Story = {
```suggestion
export const Primary: Story = {
	args: {
		variant: 'primary',
		size: 'sm',
		pill: false
	}
}

export const Secondary: Story = {
	args: {
		variant: 'secondary',
		size: 'sm',
		pill: false
	}
}

export const Warning: Story = {
	args: {
		variant: 'warning',
		size: 'md',
		pill: false
	}
}

export const Danger: Story = {
	args: {
		variant: 'danger',
		size: 'md',
		pill: true
	}
}

export const Dark: Story = {
	args: {
		variant: 'dark',
		size: 'lg',
		pill: true
	}
}

export const Success: Story = {
	args: {
		variant: 'success',
		size: 'lg',
		pill: true
	}
```

2023-11-28 20:09 UTC, simaomeyrerdooca commented on src/components/ui/badge/Badge.stories.ts
> +export const Primary: Story = {
assim abrangemos todas variações do componente

2023-12-01 12:03 UTC, simaomeyrerdooca commented
aqui pode atualizar a [us/refatoracao-de-componentes-ui](https://github.com/uxshop/design-system/tree/us/refatoracao-de-componentes-ui) com a release/3.0.0

2023-12-01 12:12 UTC, antonydosreis requested changes

2023-12-01 12:12 UTC, antonydosreis commented on .storybook/theme.scss
> +      flex-basis: 50%;
Não podemos resumir da seguinte forma?

`flex: 1 0 50%;`

2023-12-01 12:12 UTC, antonydosreis commented on .storybook/theme.scss
> +    }
Será que não podemos juntar o 2 e o 3 aqui?

```css
&:nth-of-type(2), &:nth-of-type(3) {
    flex: 0 0 50%;
}

2023-12-01 12:12 UTC, antonydosreis commented on .storybook/theme.scss
> +      border: 0 none;
`border: none;` não é suficiente aqui será?

2023-12-01 12:12 UTC, antonydosreis commented on .storybook/theme.scss
> +      -webkit-transition: all 200ms ease-out;
Por questões de desempenho, a melhor prática é animar apenas o que realmente precisamos. Da seguinte forma:

```css
transition: box-shadow 200ms ease-out, outline 200ms ease-out;

2023-12-01 12:16 UTC, vitorbruski commented
@antonydosreis essas correções não chegaram a ser feitas, a branch `us/refatoracao de componentes ui` tava desatualizada, agora ta tudo certo.
vou manter apenas as refatorações de tipagem, estilização e documentação do storybook nesse e nos seguintes prs

2023-12-04 19:36 UTC, closed without merging