[task] refatorar componente tag
uxshop/design-system pull request #161
Opened 2023-12-07 16:44 UTC by vitorbruski

## [task] refatorar componente tag

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10111)

### changes:

- alterado tokens css para os novos
- adicionado documentaçao para o storybook
- corrigido reatividade

2023-12-08 13:47 UTC, tiagotermebagy approved these changes

2023-12-08 19:37 UTC, simaomeyrerdooca requested changes

2023-12-08 20:28 UTC, vitorbruski commented on src/components/ui/tag/Tag.scss
> +	color: var(--tag-color, var(--s-color-content-on-color));
pode sim, tinha feito daquela forma pois acho um pouquinho mais bonito, mas fiz a alteração ja

2023-12-11 12:36 UTC, simaomeyrerdooca approved these changes

2023-12-11 12:36 UTC, merged