[task] refatorar componente icon
uxshop/design-system pull request #162
Opened 2023-12-07 16:45 UTC by vitorbruski

## [task] refatorar componente icon

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10098)

### changes:

- alterado tokens css para os novos
- adicionado documentaçao para o storybook
- corrigido reatividade
- corrigido variantes da fonte de icone

2023-12-08 14:07 UTC, tiagotermebagy commented on src/scss/theme.scss
> +@import url('https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200');
remover import dessas variações, não serão utilizadas

2023-12-08 19:35 UTC, simaomeyrerdooca requested changes

2023-12-08 20:29 UTC, vitorbruski commented on src/components/ui/icon/Icon.vue
> +		/* classes.push(`material-symbols-${props.type} icon`) */
não é, adicionei apenas porque acredito futuramente ser adicionado uma ou mais fontes, mas vou remover

2023-12-11 12:37 UTC, simaomeyrerdooca approved these changes

2023-12-11 12:39 UTC, merged