[task] refatorar componente color thumb
uxshop/design-system pull request #167
Opened 2023-12-07 16:52 UTC by vitorbruski

## [task] refatorar componente color thumb

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10075)

### changes:

- alterado tokens css para os novos
- adicionado documentaçao para o storybook
- corrigido reatividade

2023-12-07 20:27 UTC, lucascco approved these changes

2023-12-07 20:38 UTC, simaomeyrerdooca requested changes

2023-12-07 20:38 UTC, simaomeyrerdooca commented on src/components/ui/color-thumb/ColorThumb.vue
> +		classes.push(`-size-${props.size}`)
conforme a prop size muda o array classes vai enchendo, seria bom zerar esse array no inicio da computed

2023-12-08 19:01 UTC, tiagotermebagy approved these changes

2023-12-08 19:04 UTC, merged