[Task] Animações de dropdown no menu
uxshop/design-system pull request #179
Opened 2023-12-19 12:40 UTC by lucascco

**[Task] Animações de dropdown no menu**

[Task 9996](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2028?workitem=9996)

_Changes:_
- Inclusão das animações para uso na Sidebar
- Criação do componente de Indicador de Novidades para SideBar

2023-12-20 18:09 UTC, tiagotermebagy requested changes

2023-12-20 18:09 UTC, tiagotermebagy commented on src/components/ui/news-indicator/NewsIndicator.scss
> +	--animation-time: calc(var(--s-motion-duration-very-slow) - 1000ms);
essa variável é necessária?

2023-12-20 20:38 UTC, lucascco commented on src/components/ui/news-indicator/NewsIndicator.scss
> +	--animation-time: calc(var(--s-motion-duration-very-slow) - 1000ms);
Refletindo melhor, não vejo porque fazer esse calc com o --s-motion-duration-very-slow, coloquei o valor de duração direto, 2 segundos, pois é uma animação especifica, e os valores que temos do motion-duration, não deixaria o pulse fluido.

2023-12-21 12:28 UTC, Lima08 requested changes

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
> +		transition: background-color 0.5s;
Acredito que aqui vc poderia usar `--s-motion-duration-default`

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
>  		margin: 0 10px;
Utilizar os novos tokens

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
>  			z-index: 2;
Acredito que de pra usar ` --s-index-low`

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
>  		margin-bottom: 8px;
`--s-spacing-nano`

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
>  			font-weight: 500;
--s-font-weight-medium

2023-12-21 12:28 UTC, Lima08 commented on src/components/admin/sidebar/Sidebar.scss
>  			background-color: #e5eaef60;
Acredito que vc possa usar ` --s-color-fill-default-hover`

2023-12-22 11:23 UTC, tiagotermebagy approved these changes

2023-12-22 11:27 UTC, Lima08 approved these changes

2023-12-22 12:32 UTC, simaomeyrerdooca approved these changes

2023-12-22 18:18 UTC, merged