Task/refatora componente aside
uxshop/design-system pull request #180
Opened 2023-12-19 20:33 UTC by Lima08

## Task/refatora componente aside

### Changes:
- Refatora componente 
- Cria `stories.ts`
- Atualiza css

2023-12-19 21:08 UTC, simaomeyrerdooca requested changes

2023-12-19 21:08 UTC, simaomeyrerdooca commented on src/components/ui/aside/Aside.scss
> +				color: var(--b-color-base);
`--b-color-base` creio que não se encaixa nos novos tokens

2023-12-19 21:08 UTC, simaomeyrerdooca commented on src/components/ui/aside/Aside.vue
> +	size?: 'sm' | 'md' | 'lg'
aqui podemos usar o tipo `Size` em `src/types/Types.ts`

2023-12-19 21:16 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> -		&.-show {
Removi pois não encontrei nenhum fluxo de uso mestre Simons

2023-12-19 21:17 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> +				border-top: var(--s-border-thin);
nops. Já tem no `--s-border-thin`

2023-12-20 11:13 UTC, tiagotermebagy requested changes

2023-12-20 11:13 UTC, tiagotermebagy commented on src/components/ui/aside/Aside.scss
> +				border-top: var(--s-border-thin);
Só precisa validar se é a cor certa, pois ela vem com border color default

2023-12-20 11:13 UTC, tiagotermebagy commented on src/components/ui/aside/Aside.stories.ts
> +	render: (args) => ({
Realmente precisa o render em todos? não seria melhor fazer no meta ou com decorators?

2023-12-20 11:17 UTC, augusto-metz commented on src/components/ui/aside/Aside.scss
> +				color: var(--b-color-base);
> `--b-color-base` creio que não se encaixa nos novos tokens

2023-12-20 11:19 UTC, augusto-metz commented on src/components/ui/aside/Aside.scss
> +					background-color: var(--b-color-base);
e nesse aqui substitui o `--b-color-base` por `--s-color-content-highlight`

2023-12-20 11:35 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> +				border-top: var(--s-border-thin);
Ta certo sim mister @tiagotermebagy. To seguindo o Figma e confirmando com mestre @augusto-metz quando necessário.

2023-12-20 11:39 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> +			border-top: var(--s-border-thin);
mesmo caso anterior =]

2023-12-20 11:40 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> +			padding: 0 vat(--s-spacing-quark);
q feio

2023-12-20 11:48 UTC, Lima08 commented on src/components/ui/aside/Aside.scss
> +				color: var(--b-color-base);
A cor `--b-color-base` é a mesma da `--s-color-fill-highlight`, mas acredito que no caso realmente deve ser usada a `--s-color-fill-highlight` correto?

2023-12-20 11:50 UTC, Lima08 commented on src/components/ui/aside/Aside.stories.ts
> +	render: (args) => ({
Com `decorators` u ainda não peguei o funcionamento. Tive que usar o render por conta da reatividade do btn close não estar funcionando. Teria alguma outra forma de fazer funcionar sem dar essa volta com o render?

2023-12-20 13:29 UTC, simaomeyrerdooca approved these changes

2023-12-20 18:07 UTC, tiagotermebagy approved these changes

2023-12-21 14:21 UTC, merged