[Task]: Refatora componente button group
uxshop/design-system pull request #186
Opened 2023-12-22 12:57 UTC by Lima08

## [Task]: Refatora componente button group

[Task](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2028?workitem=10071)

## Changes:
- Remove arquivos com stories antigas
- Corrige duração das animações do componente `Dialog`
- Refatora reatividade do componente `Button` e `IconButton`
- Cria stories dos componentes `Butoon`, `ButoonGroup` e `IconButton` e atualiza tokens de css
- Realiza ajuste no componente `Icon`

2023-12-26 11:31 UTC, tiagotermebagy requested changes

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +	min-height: 38px;
min-height fixo?

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +		min-height: 30px;
min- height fixo?

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +		min-height: 50px;
min-height fixo?

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +			border: var(---s-border-thin);
var errada `---`

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +			border: var(---s-border-thin);
var errada `---`

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.scss
> +			background-color: var(-color-fill-highlight-dark);
var errada

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.stories.ts
> +	render: (args) => ({
não é necessário usar o render se não precisa manipular o template

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.vue
> +	/** Use with loading true. */
remover comentário

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/button/Button.vue
> +	return [
declarar array em uma const, e depois retornar o valor do filtro, para ficar mais legivel

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/icon-button/IconButton.scss
> +	height: 38px;
pq valores fixos? precisamos tokens para esses tamanhos caso não tenha, ver com o @augusto-metz

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/icon-button/IconButton.scss
> +    height: 30px;
mesmo caso, ver tokens para os tamanhos.

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/icon-button/IconButton.scss
> +		font-size: 24px;
outro caso, sendo que temos a prop no componente de ui-icon, então não deveria fazer essa manipulação no css.

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/icon-button/IconButton.stories.ts
> +	render: (args) => ({
Não precisa usar o render, igual o caso anterior

2023-12-26 11:31 UTC, tiagotermebagy commented on src/components/ui/icon-button/IconButton.vue
> +const computedButtonProps = computed(() => ({
é realmente necessário essa computed?

2023-12-26 12:04 UTC, Lima08 commented on src/components/ui/icon-button/IconButton.vue
> +const computedButtonProps = computed(() => ({
Tive que adicionar essa computed para os controles do story book funcionar corretamente

2023-12-26 14:06 UTC, simaomeyrerdooca commented on src/components/ui/button/Button.vue
> +	const filteredClassList = [
```suggestion
return [
  props.size ? `-${props.size}` : '',
  props.variant ? `-${props.variant}` : '-default',
  props.leadingIcon ? '-icon' : '',
  props.flush ? `-flush-${props.flush}` : '',
  props.block ? '-block' : '',
  props.outline ? '-outline' : '',
  props.disclosure ? '-disclosure' : ''
]
```
O que acha dessa solução? Assim evitamos o filter para os `undefined` e facilitamos a leitura

2023-12-26 14:06 UTC, simaomeyrerdooca commented on src/components/ui/button/Button.vue
> +const trailingIcon = computed(() => {
```suggestion
const trailingIcon = computed(() => props.disclosure ? 'arrow_drop_down' : props.trailingIcon)
```

2023-12-28 11:35 UTC, simaomeyrerdooca approved these changes

2023-12-28 13:16 UTC, tiagotermebagy requested changes

2023-12-28 13:20 UTC, Lima08 commented on src/components/ui/icon/Icon.vue
> +	<i class="ui-icon material-symbols-outlined" :style="iconStyleList">
Não temos variação. Confirmei com @augusto-metz se teria em algum momento. Como não, passei para classe fixa.

2023-12-28 13:52 UTC, Lima08 commented on src/components/ui/icon-button/IconButton.scss
> +		padding: var(--s-spacing-quark) !important;
Coloquei equivocadamente. Ajustado! 
Percebi tbm que não estava alterando o tamanho do icon, então adicionei uma logica no componente. Vê se concorda com o ajuste.

2023-12-28 18:13 UTC, tiagotermebagy approved these changes

2023-12-29 11:16 UTC, merged