[Task] Storybook Sidebar
uxshop/design-system pull request #187
Opened 2023-12-26 20:59 UTC by simaomeyrerdooca

## [Task] Storybook Sidebar

### Changes:

- Adição do storybook `.ts` e remoção da versão antiga `.js`
- Remoção de interface não mais utilizada.

2023-12-26 21:00 UTC, simaomeyrerdooca commented on src/components/admin/sidebar/Sidebar.stories.ts
> +			const menu = reactive({
essa implementação será refeita, a sidebar depende desse provide pra funcionar

2023-12-27 16:54 UTC, tiagotermebagy requested changes

2023-12-27 16:54 UTC, tiagotermebagy commented on src/components/admin/sidebar/Sidebar.stories.ts
> +				console.log('isNode', isNodeActive(node))
remover console.log

2023-12-28 11:42 UTC, tiagotermebagy approved these changes

2023-12-28 11:49 UTC, Lima08 approved these changes

2024-01-04 11:58 UTC, merged