[Task] Refatora componente form text field
uxshop/design-system pull request #193
Opened 2023-12-29 19:04 UTC by Lima08

## [Task] Refatora componente form text field 

### [TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2028?workitem=10096)

### Changes:
- Refatora componente `FormTextField` e cria stories

# ATENÇÃO:
- BRanch target será modificada para release 3 assim que finalizado pr anterior

2023-12-29 19:15 UTC, simaomeyrerdooca approved these changes

2024-01-02 17:26 UTC, vitorbruski commented on src/components/ui/form-textfield/FormTextfield.stories.ts
> +	title: 'Ui/FormTextfield',
no título podemos colocar dentro de um grupo dentro do storybook
```suggestion
	title: 'Ui/Form/Textfield',
```

acredito que também podemos ir adicionando isso aos futuros componentes adicionados e, tambem aos que ainda nao tem

2024-01-02 17:29 UTC, vitorbruski commented on src/components/ui/form-textfield/FormTextfield.stories.ts
> +export const leadingIcon: Story = {
aqui acho que podemos seguir o modelo PascalCase
```suggestion
export const LeadingIcon: Story = {
```

2024-01-02 17:29 UTC, vitorbruski commented on src/components/ui/form-textfield/FormTextfield.stories.ts
> +export const trailingIcon: Story = {
```suggestion
export const TrailingIcon: Story = {
```

2024-01-02 17:41 UTC, Lima08 commented on src/components/ui/form-textfield/FormTextfield.stories.ts
> +	title: 'Ui/FormTextfield',
Excelente ponto Vitor!

2024-01-02 17:42 UTC, Lima08 commented on src/components/ui/form-textfield/FormTextfield.stories.ts
> +	title: 'Ui/FormTextfield',
Foi fazer isso no pr https://github.com/uxshop/design-system/pull/194/files que está a frente desse, ok?

2024-01-02 18:38 UTC, simaomeyrerdooca requested changes

2024-01-02 18:38 UTC, simaomeyrerdooca commented on src/components/ui/form-textfield/FormTextfield.vue
> +import type { Size, IAction } from 'src/types'
utilizar o caminho realtivo `../../../types`

2024-01-02 18:38 UTC, simaomeyrerdooca commented on src/components/ui/form-textfield/FormTextfield.vue
> +import type { MaskOptions, MaskType } from 'maska'
o `MaskOptions` e `MaskType` pode agrupar com o import já existente na linha 3

2024-01-02 21:00 UTC, simaomeyrerdooca approved these changes

2024-01-03 12:05 UTC, vitorbruski approved these changes

2024-01-03 13:20 UTC, merged