[task] refatorar componente stack
uxshop/design-system pull request #196
Opened 2024-01-03 11:38 UTC by vitorbruski

## [task] refatorar componente stack

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10830)

### changes:

- alterado tokens css para os novos
- adicionado documentaçao para o storybook
- corrigido reatividade

2024-01-03 13:10 UTC, Lima08 requested changes

2024-01-03 13:10 UTC, Lima08 commented on src/components/ui/stack/Stack.stories.ts
> +import { ref } from 'vue'
Acredito que pode remover esse import ref

2024-01-03 13:10 UTC, Lima08 commented on src/components/ui/stack/Stack.vue
> +const stackClassList = computed(() => {
Acredito que ficaria mais simples utilizar a mesma solução que aplicamos [AQUI](https://github.com/uxshop/design-system/blob/594f7a4f984f549280d36368ee071ce419f18da0/src/components/ui/button/Button.vue) linha 38

2024-01-04 11:59 UTC, vitorbruski commented on src/components/ui/stack/Stack.vue
> +const stackClassList = computed(() => {
bem analisado, não tinha pensado em fazer dessa forma.
eu fiz todos os outros componentes nessa mesma estrutura e acho que seria viável mudar isso, vou trabalhar nisso na sequencia

2024-01-05 12:21 UTC, simaomeyrerdooca approved these changes

2024-01-05 13:00 UTC, Lima08 approved these changes

2024-01-05 13:00 UTC, Lima08 commented on src/components/ui/stack/Stack.vue
> +const stackClassList = computed(() => [
Man, alguns pontos nesse stackClassList. Segue:
- Acredito que pode remover as linhas em branco entre cada item pois como são todas do mesmo contexto acredito que facilite a leitura
- Na linha props.wrap == null && props.wrap == false && '-no-wrap', a condição está correta? Me parece q nunca será verdadeira porque props.wrap não pode ser simultaneamente null e false
- Poderia modificar os operadores != para !== de modo a checar os tipos

2024-01-05 13:00 UTC, Lima08 commented on src/components/ui/stack/Stack.vue
>  	spacing?: string
Seria possível criar um type para mostrar quais spacings são aceitos?

2024-01-19 11:51 UTC, merged