[task] refatorar componentes do grupo skeleton
uxshop/design-system pull request #197
Opened 2024-01-03 11:39 UTC by vitorbruski

## [task] refatorar componentes do grupo skeleton

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/10107)

### changes:

- alterado tokens css para os novos
- adicionado documentaçao para o storybook
- corrigido reatividade

2024-01-03 12:41 UTC, simaomeyrerdooca requested changes

2024-01-03 12:41 UTC, simaomeyrerdooca commented on src/components/ui/skeleton-table/SkeletonTable.vue
> +const skeletonTableClassList = computed(() => {
nesse caso em específico como vamos adicionar somente uma classe e é a partir de uma condição da própria `prop` podemos manter lá no `:class` sem essa computed

2024-01-03 12:49 UTC, Lima08 commented on src/components/ui/skeleton-list/SkeletonList.scss
> +		padding: var(--s-spacing-x-small) 0;
Aqui o mais proximo não seria `xx-small`?

2024-01-03 12:56 UTC, Lima08 commented on src/components/ui/skeleton/Skeleton.scss
> +		var(--s-color-neutral-200, #e0e8f2) 25%,
Não seria `--s-color-fill-default-light`? E a cor `--s-color-neutral-200 `está correta? Não encontrei entre os tokens

2024-01-03 12:58 UTC, Lima08 approved these changes

2024-01-05 11:18 UTC, vitorbruski commented on src/components/ui/skeleton-list/SkeletonList.scss
> +			border-top: var(--s-border-light);
é sim, as bordas atualmente são criadas da seguinte forma:
`$semantic-borders-width: (
	none: solid tokens.getPrimitiveVar($primitive-borders, width, 0) var(--s-color-border-default),
	light: solid tokens.getPrimitiveVar($primitive-borders, width, 1px) var(--s-color-border-default),
	thin: solid tokens.getPrimitiveVar($primitive-borders, width, 2px) var(--s-color-border-default),
	strong: solid tokens.getPrimitiveVar($primitive-borders, width, 4px) var(--s-color-border-default),
	heavy: solid tokens.getPrimitiveVar($primitive-borders, width, 8px) var(--s-color-border-default)
);`

2024-01-05 11:21 UTC, vitorbruski commented on src/components/ui/skeleton-list/SkeletonList.scss
> +		padding: var(--s-spacing-x-small) 0;
seria, mas no layout aumentou um pouco o espaçamento e agora estamos utilizando 16px

2024-01-05 11:30 UTC, vitorbruski commented on src/components/ui/skeleton/Skeleton.scss
> +		var(--s-color-neutral-200, #e0e8f2) 25%,
corrigidos, as cores estavam incorretas mesmo

2024-01-05 12:20 UTC, simaomeyrerdooca approved these changes

2024-01-05 13:10 UTC, Lima08 commented on src/components/ui/skeleton-table/SkeletonTable.vue
> +	padding: '14px',
Não sei se isso pode ou n interferir, mas nos tokens estamos usando intervalos de 4 em 4, ou seja, 4,8,12,16 etc. Faz sentido modificar esse padding default para 12 ou 16?

2024-01-05 13:11 UTC, Lima08 approved these changes

2024-01-10 11:05 UTC, merged