[Task] Refatora componente seo
uxshop/design-system pull request #211
Opened 2024-01-11 17:56 UTC by Lima08

## [Task] Refatora componente seo

#### [TASK](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/sprint%2028?workitem=11018)

### Changes:
- Cria stories e refatora css e componente Seo
- Realiza ajuste nos componente RowExclude e Alert

2024-01-11 18:34 UTC, simaomeyrerdooca requested changes

2024-01-11 18:34 UTC, simaomeyrerdooca commented on src/components/admin/seo/Seo.vue
> +export type SeoModelValue = {
Creio que poderia ser uma interface e não vejo a necessidade de adicionar `ModelValue` ao nome visto que dessa interface pode se implementar as props do SEO

2024-01-12 13:15 UTC, Lima08 commented on src/components/admin/seo/Seo.vue
> +export type SeoModelValue = {
Fiz a modificacao mas tive que manter o nome diferente de apenas Seo para nao conflitar com o nome do componente

2024-01-15 14:01 UTC, lucascco approved these changes

2024-01-16 12:59 UTC, vitorbruski approved these changes

2024-01-16 14:57 UTC, merged