Task: Refatoração da table-list
uxshop/design-system pull request #259
Opened 2024-02-08 20:22 UTC by Lima08

## [Task] Refatoração da table-list

[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront/2024/sprint%202?workitem=11626)

### Changes:

- Refatora css table list e realiza ajustes conforme nescessário

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/snippets/TableListEmptyMessage.vue
> +	border: (--s-border-light);
falou o "var"

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +		background-color: var(--s-color-fill-disable);
aqui é um componente disable pra estar usando a variavel de disable?

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +			background-color: var(--s-color-fill-disable);
aqui o status é disable e o token está como disable

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +		margin-top: var(--s-border-radius-medium);
token de borda em padding e margin?

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/table-list-table/TableListTable.scss
> +			background-color: var(--s-color-fill-disable);
token de disable no estado de hover?

2024-02-08 20:38 UTC, augusto-metz commented on src/components/admin/table-list/table-list-table/TableListTable.scss
> +		padding: var(--s-spacing-nano) var(--td-padding);
possui um token antigo ainda no padding

2024-02-08 21:12 UTC, Lima08 commented on src/components/admin/table-list/table-list-table/TableListTable.scss
> +		padding: var(--s-spacing-nano) var(--td-padding);
na verdade esse token é uma var css declarada em tableList.scss 
`--td-padding: var(--s-spacing-x-small);`
Vou remover ela e passar direto pra evitar mal entendimento

2024-02-08 21:22 UTC, Lima08 commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +		background-color: var(--s-color-fill-disable);
na verdade n, porem n encontrei cor proxima. Seria `--s-color-fill-default-light`?

2024-02-09 11:20 UTC, augusto-metz commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +		background-color: var(--s-color-fill-disable);
provavelmente sim, chegou a olhar como estava no Figma? A variável disable é somente em estados disable dos componentes

2024-02-09 11:24 UTC, augusto-metz requested changes

2024-02-09 11:24 UTC, augusto-metz commented on src/components/admin/table-list/TableList.scss
> +				color: var(--s-color-fill-default);
aqui eu acho que a cor do texto deveria ser var(--s-color-fill-on-color) nao?

2024-02-09 11:25 UTC, augusto-metz requested changes

2024-02-09 11:25 UTC, augusto-metz commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.scss
> +					margin-right: var(--s-border-radius-medium);
token de borda em margin?

2024-02-09 19:24 UTC, augusto-metz approved these changes

2024-02-09 19:31 UTC, simaomeyrerdooca approved these changes

2024-02-09 19:43 UTC, merged