[Task] Adiciona props em media card
uxshop/design-system pull request #314
Opened 2024-03-11 18:47 UTC by Lima08

…card de media card

## [Task] Task title board

[task link](https://dev.azure.com/doocacom/Platform/_workitems/edit/11778/)

### Changes:

- Adiciona prop `horizontal` para definir forma de exibicao do coimponente `MediaCard`

2024-03-11 20:28 UTC, simaomeyrerdooca requested changes

2024-03-11 20:28 UTC, simaomeyrerdooca commented on src/components/admin/media-card/MediaCard.vue
> +if (props.horizontal) mediaCardClasses.value.push('-horizontal')
pra dar uma melhorada nas visualização e reatividade dessas classes podemos usar uma `computed` retornando condicionalmente as classes no array

2024-03-12 13:45 UTC, simaomeyrerdooca commented on src/components/admin/media-card/MediaCard.vue
> +const mediaCardClasses = computed<string[]>(() => {
para não usarmos os push no array podemos já cria-lo condicionalmente com essas duas sugestões:

```
const openModal = ref<boolean>(false)
  const mediaCardClasses = computed<string[]>(() => {
  return [
    "ui-media-card",
    props.inverse && '-inverted',
    props.video && '-video',
    props.horizontal && '-horizontal'
  ].filter(styleClass => styleClass)
})

const mediaCardClasses = computed<string[]>(() => {
  return [
    "ui-media-card",
    props.inverse ? '-inverted' : '',
    props.video ? '-video' : '',
    props.horizontal ? '-horizontal' : '',
  ]
})
```

2024-03-12 18:22 UTC, lucascco commented on src/components/admin/media-card/MediaCard.vue
> +	return [
Neste caso não podemos usar o bind de class:
Seria:
return {
'ui-media-card': true
'-inverted': props.inverse,
'-video': props.video,
'-horizontal': props.horizontal
}

2024-03-12 18:48 UTC, lucascco approved these changes

2024-03-12 18:48 UTC, merged