Us/banners dinamicos
uxshop/design-system pull request #322
Opened 2024-03-19 18:07 UTC by Lima08

## [US] BAnners dinamicso

[us link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-backoffice/Platform/backoffice/2024/sprint%203?workitem=11611)

2024-03-19 18:43 UTC, augusto-metz commented on src/components/admin/media-card/MediaCard.scss
> +  }
Aqui precisamos alterar o border-radius. Tem que deixar igual o de mobile.

Atualmente, está errado, segue print.

![image](https://github.com/uxshop/design-system/assets/151647208/e0d47282-a030-4479-b220-e83a89633fbf)

2024-03-19 20:16 UTC, Lima08 commented on src/components/admin/media-card/MediaCard.scss
> +  }
como diria Platão, mestre jedi da segunda guerra mundial pokemon: "Se augusto quer Augusto tem"
Segue aqui --> https://github.com/uxshop/design-system/pull/323

2024-03-26 16:50 UTC, simaomeyrerdooca requested changes

2024-03-26 16:50 UTC, simaomeyrerdooca commented on src/components/admin/media-card/MediaCard.vue
> +			<a :href="imageHref" target="_blank">
esse `href` um dia não pode ser `target="_self"`

2024-03-26 17:21 UTC, Lima08 commented on src/components/admin/media-card/MediaCard.vue
> +			<a :href="imageHref" target="_blank">
Um  dia talvez, mas ate o momento nao temos esse caso de uso.

2024-03-26 17:36 UTC, simaomeyrerdooca approved these changes

2024-03-26 21:01 UTC, augusto-metz requested changes
@Lima08, vamos adicionar um props de max-height no ui-media-card-image para que os banners não fiquem estourados.

2024-03-27 19:02 UTC, closed without merging