[fix] ajustes visuais do painel de controle
uxshop/design-system pull request #333
Opened 2024-04-01 15:41 UTC by vitorbruski

## [fix] ajustes visuais do painel de controle

[fix link](https://dev.azure.com/doocacom/Platform/_workitems/edit/12638)

### changes:

- ajustado paddings de `Col`
- adicionado prop `noWrap` para `Badge`
- corrigido agrupamento dos campos no mobile
- removido margin negativa em link dentro de `Card`

2024-04-02 11:39 UTC, Lima08 commented on src/components/ui/badge/Badge.vue
> +	props.pill && '-pill',
nao teria que filtrar os campos para nao ficar um array com valores nulos?

2024-04-02 11:40 UTC, Lima08 commented on src/components/ui/grid/col/Col.scss
>  	// margin-top: var(--grid-gutter-width);
acredito que possa remover esse comentario

2024-04-02 11:41 UTC, Lima08 approved these changes

2024-04-02 11:45 UTC, simaomeyrerdooca commented on src/components/ui/badge/Badge.vue
> +	props.pill && '-pill',
isso ou

```
props.size ? `-size-${props.size}` : '',
props.variant ? `-variant-${props.variant}` : '',
props.noWrap ? '-no-wrap' : ''
```

2024-04-02 11:49 UTC, vitorbruski commented on src/components/ui/badge/Badge.vue
> +	props.pill && '-pill',
nesse caso acredito não ter problema pq são classes opcionais, a classe do próprio componente ja foi injetada separadamente

2024-04-02 14:22 UTC, simaomeyrerdooca requested changes

2024-04-02 14:22 UTC, simaomeyrerdooca commented on src/components/ui/badge/Badge.vue
> +const badgeClassList = badgeClasses.value.filter((badgeClass) => badgeClass)
dessa forma perderemos a reatividade, a const deve estar dentro da computed

Segue exemplo:
```
const badgeClasses = computed(() => {
  const badgeClassList =  [
		props.pill && '-pill',
		props.size && `-size-${props.size}`,
		props.variant && `-variant-${props.variant}`,
		props.noWrap && '-no-wrap'
	]

  return badgeClassList.filter((badgeClass) => badgeClass)
})
```

2024-04-02 15:13 UTC, vitorbruski commented on src/components/ui/badge/Badge.vue
> +const badgeClassList = badgeClasses.value.filter((badgeClass) => badgeClass)
bem observado, corrigido

2024-04-03 13:38 UTC, vitorbruski commented
@simaomeyrerdooca e @Lima08, novas alterações feitas:

- adicionado ellipsis para o titulo do produto, no detalhe do produto
- adicionado padding para espaçamento entre titulo e dropdown de `Mais ações`

por favor, deem uma olhada nas alterações novamente

2024-04-03 13:42 UTC, simaomeyrerdooca commented
> @simaomeyrerdooca e @Lima08, novas alterações feitas:
> 
> * adicionado ellipsis para o titulo do produto, no detalhe do produto
> * adicionado padding para espaçamento entre titulo e dropdown de `Mais ações`
> 
> por favor, deem uma olhada nas alterações novamente

@vitorbruski  pode colocar as alterações dessa branch na `release/homolog`, depois subir um empty commit pra homolog no admin-platform e avisar o Augusto que as alterações foram feitas

2024-04-03 15:02 UTC, vitorbruski commented
@simaomeyrerdooca subi as atualizações pra homolog

2024-04-03 20:29 UTC, simaomeyrerdooca approved these changes

2024-04-03 20:57 UTC, Lima08 approved these changes

2024-04-04 11:12 UTC, merged