[Task] Criar tratamento de erro na instalação do App
uxshop/design-system pull request #339
Opened 2024-04-04 19:46 UTC by lucascco

## [Task] Criar tratamento de erro na instalação do App

[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-suite/Platform/suite/2024/sprint%203?workitem=12944)

### Changes:

- Inclusão do slot caption no componente de Modal para satisfazer as necessidades do modal de instalação de app no marketplace

2024-04-04 20:25 UTC, simaomeyrerdooca requested changes

2024-04-04 20:25 UTC, simaomeyrerdooca commented on src/components/ui/modal/Modal.vue
> +							<span v-if="haveSlot('caption')" class="ui-modal-caption"> <slot name="caption" /></span>
será que não seria melhor deixar somente o slot? digo porque talvez em algum uso vamos querer outra tag e não somente o span

2024-04-04 20:32 UTC, simaomeyrerdooca approved these changes

2024-04-04 20:44 UTC, simaomeyrerdooca approved these changes

2024-04-05 12:31 UTC, ryanlaiber approved these changes

2024-04-05 13:12 UTC, merged