[release/hub] Ajustes gerais
uxshop/design-system pull request #385
Opened 2024-09-26 17:47 UTC by rhandrade

## [release/hub] Ajustes gerais 

Alterações necessários para resolver problemas de importação e build pelos aplicativos que usam o Design System, bem como atualizar dependências do projeto para a versão mais recente compatível.

**Changes:**
- Remove cypress 067b84d 76ec4eb
- Muda o padrão de formatação do Prettier 76ec4eb 
- Atualiza dependencias gerais 76ec4eb 
- Remove pacotes desnecessários do Webpack 76ec4eb 
- Adiciona configurações específicas do tsconfig para Node e Vitest 76ec4eb 
- Adiciona tipos do player do Youtube 59de60c 
- Remove git-commit-msg-linter em detrimento do commitlint 1f454a2 
- Adota padrão conventional commits 1f454a2 
- Modifica comportamento nos hooks commit-msg, pre-commit e pre-push do git 1f454a2 d55559f 
- Atualiza página inicial para testes 6670bf9 
- Atualiza @simonwep/pickr para projeto original em detrimento ao fork e652959 
- Atualiza codemirror para v6 53757ef 
- Atualiza eslint para v9 d55559f 
- Atualiza storybook para v8 383a345
- Corrige erros de tipo e lógica devido a atualização das dependencias 59de60c
    - BrowserSelectModal.vue: Substitui `clone` e `deepClone` do lodash por `structuredClone` javascript
    - Sidebar.vue: Cria um computed para lidar com links
    - TableListNavCustomFilter.vue: Remove `each` do lodash por `forEach` do javascript
    - DescriptionList.vue: Fix component export
    - FormSpinbutton.vue: Improved type number assertion and validation

**BREAKING CHANGES**
- Muda modo de realizar a chegagem de tipos 76ec4eb 
- Atualiza versão mínima exigida do Node para `node>=20.10.0` 76ec4eb  b9221d2 
- Remove plugin Prettier eslint 76ec4eb 
- Atualiza Sass, Typescript, Vite, Vitest e @vue/tsconfig para versão compatível mais recente  76ec4eb 
- Remove alias typescript em detrimento ao node subpath imports 76ec4eb 
- Restringe itens exportados e disponíveis para terceiros 76ec4eb 1f454a2 
- Substitui yarn pelo npm 76ec4eb 
- Adiciona lockfile no projeto b9b28f8 
- Corrige erros de tipo e lógica devido a atualização das dependências 59de60c
    - TableCell.vue: altera prop `onAction` para `action`;
    - ColorThumb.vue: prop `image` agora suporte somente strings;
    - FormCurrency.vue: props `min`, `max` agora suportam somente números. Altera o tipo da prop `options` para `CurrencyInputOptions`;
    - FormDatepicker.vue: update emit now defaults to null and accept string as param value

2024-09-27 17:27 UTC, tiagotermebagy requested changes

2024-09-27 17:27 UTC, tiagotermebagy commented on .prettierrc
> +  "semi": true,
@rhandrade normalmente não usamos `;`

2024-09-27 17:27 UTC, tiagotermebagy commented on src/components/admin/browser-select/BrowserSelectModal.vue
> +// const props = defineProps<BrowserSelectProps>();
acredito que podemos remover se não será utilizado

2024-09-27 17:27 UTC, tiagotermebagy commented on .prettierrc
> +  "useTabs": false,
acredito que podemos manter os `useTabs`

2024-09-27 17:27 UTC, tiagotermebagy commented on vite.config.ts
> -			'@': fileURLToPath(new URL('./src', import.meta.url))
Não foi possível manter o alias?

2024-09-27 17:28 UTC, simaomeyrerdooca requested changes

2024-09-27 17:28 UTC, simaomeyrerdooca commented on .prettierrc
> +  "trailingComma": "es5",
acredito que podemos manter o `none` aqui, penso muito nos arquivos que já temos, se precisarmos modificar uma linha do código todo o arquivo vai ser atualizado

2024-09-27 20:55 UTC, rhandrade commented on .prettierrc
> +  "semi": true,
@tiagotermebagy Eu adicionei a obrigatoriedade do `;` porque já tivemos problemas com erros quando removido. Validei também com a comunidade e vários projetos grandes ainda preferem o uso, citando como principais motivos:
- Garantir compatibilidade versões antigas;
- Maior facilidade de leitura do código;
- Menor propensão a erros;
- Compatibilidade com ferramentas que não suportam ASI

Dentre projetos grandes que usam temos alguns como Vscode, React, Polaris, Angular, Axios e Apollo.

Acredito que o benefício de manter o `;` é maior do que remover.

2024-09-27 21:17 UTC, rhandrade commented on .prettierrc
> +  "useTabs": false,
@tiagotermebagy Praticalmente o mesmo ponto que o anterior. Eu adicionei a obrigatoriedade para usar espaços ao invés de tabs porque já tivemos problemas, principalmente quando usados por pessoas em diferentes sistemas operacionais, que tendem a renderizar tabulação de modo diferente. 

Validei também na comunidade e vários projetos grandes ainda preferem o uso, como React, Vue, Polaris, Angular, Apollo, Axios, Vite.

Pelos problemas que eu já tive no passado eu prefiro manter usando espaços.

2024-09-27 21:22 UTC, rhandrade commented on vite.config.ts
> -			'@': fileURLToPath(new URL('./src', import.meta.url))
@tiagotermebagy Não. Quando deixamos o alias no tsconfig, qualquer projeto que utilizar deverá gerar o mesmo alias, caso contrário não será possível encontrar os arquivos do projeto do DS. Olhando as documentações do node e do turborepo verificamos que o node já possível isso nativamente com o [Subpath Imports](https://nodejs.org/api/packages.html#subpath-imports), que é importado automaticamente pelo tsconfig. A unica restrição é que precisa começar com `#`, visto que de qualquer outra forma ele acha que é uma dependência instalada.

2024-09-27 21:27 UTC, rhandrade commented on .prettierrc
> +  "trailingComma": "es5",
@simaomeyrerdooca Esse é um dos side effects, mas essa configuração ajuda muito a evitar erros no desenvolvimento, além de já deixar o código preparado para uma rápida inserção quando novos itens serem necessários. Já evitamos vários erros devido a essa configuração, que depois para achar é bem problemático.

Quanto as alterações, já vai gerar bastante modificação devido as outras regras que eu alterei do prettier, portanto não vejo um problema. Outro ponto é que as alterações podem ser minimizadas realizando um commit só para refatorar o código baseado no prettier, e depois disso o código passa a ter sempre as alterações que foram pertinentes, isso é tranquilo de fazer.

2024-09-27 21:27 UTC, rhandrade commented on src/components/admin/browser-select/BrowserSelectModal.vue
> +// const props = defineProps<BrowserSelectProps>();
Removido.

2024-10-03 19:11 UTC, tiagotermebagy approved these changes

2024-10-03 19:37 UTC, simaomeyrerdooca approved these changes

2024-10-04 10:12 UTC, merged