`feature/improve-export` Padroniza todos os exports dos componentes
uxshop/design-system pull request #390
Opened 2024-10-22 15:04 UTC by rhandrade

#### Descrição

Padroniza todos os exports dos componentes nas suas respectivas pastas. Todos os componentes disponíveis na pasta `components` foram exportados. Atrelado, exporta também todas as propriedades que os componentes podem receber.

#### Breaking changes
- admin/stats-group - renomeado a pasta de stats para stats-group
- ui/aside - Modificado exportação index anterior
- ui/breadcrumb - Modificado exportação index anterior
- ui/card - Modificado exportação index anterior
- ui/dialog - Modificado exportação index anterior, removido exportação default do código .ts
- export Select removido
- ui/form-wrapper - removido arquivos de tipagem incorretos
- ui/grid - Modificado exportação index anterior
- ui/list-group - Modificado exportação index anterior
- ui/modal - Modificado exportação index anterior
- ui/pagination - Modificado exportação index anterior
- ui/spinner - Removido type style
- ui/tab - Modificado exportação index anterior
- ui/toast - Modificado exportação index anterior, removido exportação default do código .ts

2024-10-22 17:34 UTC, simaomeyrerdooca requested changes

2024-10-22 20:44 UTC, rhandrade commented on src/components/admin/card-seo/types.ts
> +  modelValue: SeoInterface;
@simaomeyrerdooca Eu não cheguei a fazer alterações quando a ordenação, eu só peguei de dentro do arquivo do componente e adicionei no arquivo de tipos.

2024-10-22 20:44 UTC, rhandrade commented on src/components/admin/sidebar-header/types.ts
> +  actionsConfig: {
@simaomeyrerdooca Eu não cheguei a fazer alterações quando a ordenação, eu só peguei de dentro do arquivo do componente e adicionei no arquivo de tipos.

2024-10-22 20:44 UTC, rhandrade commented on src/components/admin/stats-group/types.ts
> +  primaryAction?: { text: string; to?: object; href?: string; button?: boolean }[];
@simaomeyrerdooca Eu não cheguei a fazer alterações quando a ordenação, eu só peguei de dentro do arquivo do componente e adicionei no arquivo de tipos.

2024-11-01 12:31 UTC, tiagotermebagy approved these changes

2024-11-01 12:39 UTC, simaomeyrerdooca approved these changes

2024-11-01 12:41 UTC, merged