[Task] Relatórios de pedidos
uxshop/design-system pull request #66
Opened 2022-10-06 21:15 UTC by gabrielwdooca

## [Task] Relatórios de pedidos
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/Suporte%20Team/Stories/?workitem=2935)
### Changes:
- Inserido o date picker nos filtros da tabela.

2022-10-07 18:52 UTC, tiagotermedooca requested changes

2022-10-10 21:06 UTC, gabrielwdooca commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue
>  	if (filter.type == 'checkbox') {
Acho que agora está melhor.

2022-10-10 21:06 UTC, gabrielwdooca commented on src/components/admin/table-list/table-list-tags/TableListTags.vue
> +	if (key == 'created_at'){
Organizei melhor em uma função.

2022-10-11 10:36 UTC, tiagotermedooca approved these changes

2022-10-13 11:04 UTC, merged