fix: filtro de categoria com browser select
uxshop/design-system pull request #75
Opened 2022-10-26 18:17 UTC by gabrielwdooca

## [Task] Manas T - Divergência no filtro de Produtos
[task link](https://dev.azure.com/doocacom/Platform/_boards/board/t/squad-support/Stories/?workitem=3076)
### Changes:
- Adicionada a opção de filtro por browser select e a tag de category_ids

2022-10-26 20:16 UTC, simaomeyrerdooca requested changes

2022-10-26 20:16 UTC, simaomeyrerdooca commented on src/components/admin/table-list/table-list-nav-filter/TableListNavFilterSidebar.vue
> +							<browser-select
aqui pode usar como no import `<BrowserSelect>`

2022-10-26 20:16 UTC, simaomeyrerdooca commented on src/components/admin/browser-select/BrowserSelect.vue
> +					<div v-if="!templateCustom" class="browser-list-cell">
quando vimos isso aqui eu não cheguei a perguntar mas, chegou a testar se essa alteração não impacta em outros lugares onde está sendo usando esse componente?

2022-10-28 13:42 UTC, simaomeyrerdooca approved these changes

2022-10-28 14:16 UTC, antonydosreis approved these changes

2022-10-28 14:25 UTC, merged