[Task] Refatora estilização Breadcrumb
uxshop/design-system pull request #82
Opened 2023-01-05 12:41 UTC by Lima08

[task link](https://dev.azure.com/doocacom/Platform/_sprints/taskboard/squad-storefront/Platform/storefront-5?workitem=5378)

### Changes:
- Refatora css adicionando comportamento para telas mobile e deskTop
- Adiciona icone

[figma](https://www.figma.com/file/LzmW3VpvVbsj0vYEqc3JI1/Componentes---Dooca?node-id=27%3A645&t=fSoiYuAvwpuAktvr-0)

2023-01-05 12:54 UTC, simaomeyrerdooca approved these changes

2023-01-05 13:17 UTC, tiagotermedooca requested changes

2023-01-05 13:17 UTC, tiagotermedooca commented on src/components/ui/breadcrumb/BreadCrumb.scss
> +	@include mobile {
usamos mobile first ☺️ , nesse caso é bom inverter a logica

2023-01-05 13:31 UTC, antonydosreis requested changes

2023-01-05 13:31 UTC, antonydosreis commented on src/components/ui/breadcrumb/UiBreadcrumb.vue
> +	}>(),
Aqui realmente precisa do valor default? O não prover a prop icon ja não faz a validação ter o mesmo funcionamento?

2023-01-05 13:43 UTC, diovaniBelleboni approved these changes

2023-01-05 14:05 UTC, Lima08 commented on src/components/ui/breadcrumb/UiBreadcrumb.vue
> +	}>(),
Positivo mister @antonydosreis!

2023-01-05 14:09 UTC, antonydosreis approved these changes

2023-01-12 11:45 UTC, tiagotermedooca approved these changes

2023-01-12 11:46 UTC, merged